name: GamiLearn
description: "Belajar dengan menyenangkan"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_onboarding_slider: ^1.0.11
  google_fonts: ^6.2.1
  audioplayers: ^6.2.0
  timezone: ^0.10.0
  flutter_localization: ^0.3.1
  pushable_button: ^0.0.4
  flutter_custom_clippers: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/background/
  - assets/images/component/
  - assets/images/icon/
  - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon/appIcon.png"

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        weight: 400 
      - asset: assets/fonts/opensans/OpenSans-Bold.ttf
        weight: 700
